import streamlit as st
import pandas as pd
from datetime import datetime
import time
import re
import threading
import subprocess
from pathlib import Path
import math

class RecordOperationsHandler:
    def __init__(self, discogs_handler=None, ebay_handler=None):
        self.discogs_handler = discogs_handler
        self.ebay_handler = ebay_handler
    
    def add_inventory_record(self, record_data, genre, search_term):
        """Add inventory record to database with Discogs condition selection"""
        if genre is None:
            raise Exception("genre parameter is required but was None")
            
        print(f"🔴 DEBUG add_inventory_record: genre={genre}")
        
        release_id = record_data.get('discogs_id')
        
        if not release_id:
            st.error("No release ID found")
            return False, None
        
        # Get format from session state or default
        format_selected = st.session_state.get('format_select', 'Vinyl')
        
        # Get Discogs pricing information - USE PRICE SUGGESTIONS
        pricing_data = None
        
        print(f"🔴 DEBUG calling get_release_statistics_pricing")
        
        if self.discogs_handler:
            with st.spinner("Fetching Discogs price suggestions..."):
                pricing_data = self.discogs_handler.get_release_statistics_pricing(str(release_id))
            
            print(f"🔴 DEBUG pricing_data result: {pricing_data}")
        else:
            st.error("Discogs handler not available")
            return False, None
        
        # Extract result information - use the edited artist name if available
        artist = record_data.get('artist', '')  # This will be the edited version
        title = record_data.get('title', '')    # This will be the edited version
        image_url = record_data.get('image_url', '')
        catalog_number = record_data.get('catalog_number', '')
        youtube_url = record_data.get('youtube_url', '')  # Get YouTube URL from record data
        
        # Get selected condition and price from record_data
        selected_condition = record_data.get('selected_condition')
        selected_price = record_data.get('selected_price')
        
        # Get genre_id for the genre
        genre_id = None
        if genre:
            conn = st.session_state.db_manager._get_connection()
            cursor = conn.cursor()
            cursor.execute('SELECT id FROM genres WHERE genre_name = ?', (genre,))
            genre_result = cursor.fetchone()
            if genre_result:
                genre_id = genre_result[0]
            else:
                # Create new genre
                cursor.execute('INSERT INTO genres (genre_name) VALUES (?)', (genre,))
                genre_id = cursor.lastrowid
                conn.commit()
            conn.close()
        
        # Calculate file_at for confirmation message
        file_at_value = self._calculate_file_at(artist, genre)
        
        # Store pricing data in record_data for display
        if pricing_data:
            record_data['price_suggestions'] = pricing_data.get('price_suggestions', {})
        
        # CALCULATE STORE PRICE USING CONFIGURABLE PARAMETERS
        store_price = self._calculate_store_price(selected_price)
        
        # Get eBay sell price from record_data if available
        ebay_sell_at = record_data.get('ebay_sell_at', 0.0)
        
        # Save to database - include calculated store price and Discogs condition
        result_data = {
            'artist': artist,  # Use the edited artist name
            'title': title,    # Use the edited title
            'barcode': '',  # Will be generated by trigger
            'genre_id': genre_id,
            'image_url': image_url,
            'discogs_suggested_price': selected_price,
            'catalog_number': catalog_number,
            'format': format_selected,
            'condition': selected_condition,  # Store the Discogs condition text
            'file_at': file_at_value,  # Use calculated file_at
            'store_price': store_price,  # CALCULATED STORE PRICE
            'ebay_sell_at': ebay_sell_at,  # CALCULATED EBAY SELL PRICE
            'youtube_url': youtube_url  # Include YouTube URL
        }
        
        record_id = st.session_state.db_manager.save_record(result_data)
        
        # Trigger GitHub sync after successful addition
        if record_id:
            self._trigger_github_sync()
        
        return True, record_id

    def _calculate_store_price(self, selected_price):
        """Calculate store price using configurable parameters"""
        # Get current configuration
        lowest_multiplier = float(st.session_state.db_manager.get_config_value('STORE_PRICE_LOWEST_MULTIPLIER', '1.1'))
        estimated_multiplier = float(st.session_state.db_manager.get_config_value('STORE_PRICE_ESTIMATED_MULTIPLIER', '0.9'))
        minimum_price = float(st.session_state.db_manager.get_config_value('STORE_PRICE_MINIMUM', '4.99'))
        
        candidates = []
        
        if selected_price and selected_price > 0:
            # Use the selected price with the estimated multiplier
            candidates.append(selected_price * estimated_multiplier)
        
        if candidates:
            raw_price = max(candidates)
            raw_price = max(raw_price, minimum_price)
        else:
            raw_price = minimum_price
        
        # Round to nearest .49 or .99
        store_price = self._round_to_49_or_99(raw_price)
        
        return store_price

    def _round_to_49_or_99(self, price):
        """Round to nearest .49 or .99"""
        if price <= 0:
            return 0.0
        
        base_price = math.floor(price)
        decimal_part = price - base_price
        
        if decimal_part < 0.25:
            return base_price + 0.49
        elif decimal_part < 0.75:
            return base_price + 0.49
        else:
            return base_price + 0.99

    def _calculate_file_at(self, artist, genre):
        """Calculate file_at value for an artist and genre"""
        if not artist:
            return "?"
        
        artist_clean = artist.strip().lower()
        
        if artist_clean.startswith('the '):
            artist_clean = artist_clean[4:]
        
        if artist_clean and artist_clean[0].isdigit():
            number_words = {
                '0': 'zero', '1': 'one', '2': 'two', '3': 'three', '4': 'four',
                '5': 'five', '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine'
            }
            first_char = artist_clean[0]
            file_at_letter = number_words.get(first_char, '?')[0].upper()
        elif artist_clean and artist_clean[0].isalpha():
            file_at_letter = artist_clean[0].upper()
        else:
            file_at_letter = "?"
        
        return f"{genre}({file_at_letter})"

    def update_database_record(self, record_data, genre):
        """Update database record"""
        if genre is None:
            raise Exception("genre parameter is required but was None")
            
        print(f"🔴 DEBUG update_database_record: genre={genre}")
        
        record_id = record_data['id']
        
        # Get genre_id for the genre
        genre_id = None
        if genre:
            conn = st.session_state.db_manager._get_connection()
            cursor = conn.cursor()
            cursor.execute('SELECT id FROM genres WHERE genre_name = ?', (genre,))
            genre_result = cursor.fetchone()
            if genre_result:
                genre_id = genre_result[0]
            conn.close()
        
        updates = {
            'genre_id': genre_id
        }
        
        success = st.session_state.db_manager.update_record(record_id, updates)
        
        # Trigger GitHub sync after successful update
        if success:
            self._trigger_github_sync()
        
        return success

    def _trigger_github_sync(self):
        """Trigger GitHub sync in background thread"""
        def sync_background():
            try:
                # Import here to avoid circular imports
                from handlers.github_sync_handler import GitHubSyncHandler
                
                # Get the gallery JSON manager from session state
                gallery_json_manager = st.session_state.get('gallery_json_manager')
                if gallery_json_manager:
                    # Rebuild JSON first
                    gallery_json_manager.trigger_rebuild(async_mode=False)
                    
                    # Then trigger GitHub sync
                    github_handler = GitHubSyncHandler(
                        repo_path="/home/arjan-ubuntu/Documents/PigStyle",
                        gallery_json_manager=gallery_json_manager
                    )
                    github_handler.trigger_sync()
            except Exception as e:
                print(f"Background sync failed: {e}")
        
        # Start sync in background thread
        sync_thread = threading.Thread(target=sync_background, daemon=True)
        sync_thread.start()